version: '3.5'
services:
  clickhouse-server:
    container_name: my-clickhouse-server
    image: clickhouse/clickhouse-server
    ports:
      - '18123:8123'
      - '19000:9000'
    volumes:
      - './named_collections.xml:/etc/clickhouse-server/config.d/named_collections.xml'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    extra_hosts:
      - 'host.docker.internal:host-gateway'
