// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createCategory = `-- name: CreateCategory :execresult
INSERT INTO categories (
    id, en_name, create_time, update_time
)
VALUES (?, ?, ?, ?)
`

type CreateCategoryParams struct {
	ID         int64
	EnName     string
	CreateTime time.Time
	UpdateTime time.Time
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCategory,
		arg.ID,
		arg.EnName,
		arg.CreateTime,
		arg.UpdateTime,
	)
}

const createEvent = `-- name: CreateEvent :execresult
INSERT INTO events (
    id, en_name, start_time, end_time,
    category_id, create_time, update_time
)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateEventParams struct {
	ID         int64
	EnName     string
	StartTime  time.Time
	EndTime    sql.NullTime
	CategoryID int64
	CreateTime time.Time
	UpdateTime time.Time
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEvent,
		arg.ID,
		arg.EnName,
		arg.StartTime,
		arg.EndTime,
		arg.CategoryID,
		arg.CreateTime,
		arg.UpdateTime,
	)
}
